// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    agent_versions: {
        name: "agent_versions";
        parameters: {
          /** STRING - use sql.string() */
          agent_name: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          agent_version: string;
          /** @sqlType INT */
          n_traces: number;
          /** @sqlType INT */
          n_traces_total: number;
          /** @sqlType DOUBLE */
          total_tokens: number;
          /** @sqlType DOUBLE */
          tokens_per_trace: number;
          /** @sqlType DOUBLE */
          total_tool_calls: number;
          /** @sqlType DOUBLE */
          redundancy_rate: number;
          /** @sqlType DOUBLE */
          total_cost_usd: number;
          /** @sqlType BOOLEAN */
          cost_priced: boolean;
          /** @sqlType STRING */
          basis: string;
          /** @sqlType STRING */
          source: string;
        }>;
      };
    agents: {
        name: "agents";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          agent_name: string;
          /** @sqlType STRING */
          experiment_id: string;
          /** @sqlType STRING */
          description: string;
        }>;
      };
    by_model: {
        name: "by_model";
        parameters: {
          /** STRING - use sql.string() */
          experiment_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          model: string;
          /** @sqlType BIGINT */
          sessions: number;
          /** @sqlType BIGINT */
          total_tokens: number;
          /** @sqlType DOUBLE */
          est_cost_usd: number;
          /** @sqlType BIGINT */
          tool_calls: number;
        }>;
      };
    by_producer: {
        name: "by_producer";
        parameters: {
          /** STRING - use sql.string() */
          experiment_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          producer: string;
          /** @sqlType BIGINT */
          sessions: number;
          /** @sqlType BIGINT */
          total_tokens: number;
          /** @sqlType DOUBLE */
          est_cost_usd: number;
          /** @sqlType BIGINT */
          tool_calls: number;
        }>;
      };
    corpus_summary: {
        name: "corpus_summary";
        parameters: {
          /** STRING - use sql.string() */
          experiment_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          trace_count: number;
          /** @sqlType BIGINT */
          total_tokens: number;
          /** @sqlType BIGINT */
          total_input_tokens: number;
          /** @sqlType BIGINT */
          total_output_tokens: number;
          /** @sqlType DOUBLE */
          median_tokens: number;
          /** @sqlType DOUBLE */
          mean_tokens: number;
          /** @sqlType DOUBLE */
          p90_tokens: number;
          /** @sqlType BIGINT */
          max_tokens: number;
          /** @sqlType BIGINT */
          min_tokens: number;
          /** @sqlType BIGINT */
          total_tool_calls: number;
          /** @sqlType DOUBLE */
          redundancy_rate: number;
          /** @sqlType DOUBLE */
          total_cost_usd: number;
          /** @sqlType INT */
          priced_traces: number;
          /** @sqlType INT */
          unpriced_traces: number;
        }>;
      };
    high_token_sessions: {
        name: "high_token_sessions";
        parameters: {
          /** STRING - use sql.string() */
          experiment_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          trace: string;
          /** @sqlType STRING */
          model: string;
          /** @sqlType BIGINT */
          total_tokens: number;
          /** @sqlType BIGINT */
          input_tokens: number;
          /** @sqlType BIGINT */
          output_tokens: number;
          /** @sqlType INT */
          tools: number;
          /** @sqlType DOUBLE */
          duration_s: number;
          /** @sqlType DOUBLE */
          est_cost_usd: number;
          /** @sqlType BOOLEAN */
          cost_priced: boolean;
          /** @sqlType DOUBLE */
          redundancy_rate: number;
        }>;
      };
    session_token_bars: {
        name: "session_token_bars";
        parameters: {
          /** STRING - use sql.string() */
          experiment_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          trace: string;
          /** @sqlType BIGINT */
          total_tokens: number;
        }>;
      };
    tool_waste_files: {
        name: "tool_waste_files";
        parameters: {
          /** STRING - use sql.string() */
          experiment_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          trace: string;
          /** @sqlType STRING */
          tool: string;
          /** @sqlType INT */
          repeat_count: number;
          /** @sqlType INT */
          trace_tools: number;
          /** @sqlType STRING */
          path: string;
        }>;
      };
    tool_waste_shell: {
        name: "tool_waste_shell";
        parameters: {
          /** STRING - use sql.string() */
          experiment_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          trace: string;
          /** @sqlType STRING */
          tool: string;
          /** @sqlType INT */
          repeat_count: number;
          /** @sqlType INT */
          trace_tools: number;
          /** @sqlType STRING */
          prologue: string;
        }>;
      };
    version_comparisons: {
        name: "version_comparisons";
        parameters: {
          /** STRING - use sql.string() */
          agent_name: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          baseline_version: string;
          /** @sqlType STRING */
          candidate_version: string;
          /** @sqlType STRING */
          objective_metric: string;
          /** @sqlType STRING */
          status: string;
          /** @sqlType STRING */
          readiness_tier: string;
          /** @sqlType BOOLEAN */
          can_prove_improvement: boolean;
          /** @sqlType INT */
          trace_count: number;
          /** @sqlType BOOLEAN */
          frozen_suite_present: boolean;
          /** @sqlType INT */
          n_promote: number;
          /** @sqlType INT */
          n_block: number;
          /** @sqlType INT */
          n_errored: number;
          /** @sqlType BOOLEAN */
          correctness_held: boolean;
          /** @sqlType STRING */
          proof_source: string;
          /** @sqlType STRING */
          headline_metric: string;
          /** @sqlType DOUBLE */
          headline_baseline: number;
          /** @sqlType DOUBLE */
          headline_candidate: number;
          /** @sqlType DOUBLE */
          headline_delta_pct: number;
          /** @sqlType BOOLEAN */
          headline_improved: boolean;
          /** @sqlType STRING */
          reasons: string;
        }>;
      };
    version_metric_deltas: {
        name: "version_metric_deltas";
        parameters: {
          /** STRING - use sql.string() */
          agent_name: SQLStringMarker;
          /** STRING - use sql.string() */
          baseline_version: SQLStringMarker;
          /** STRING - use sql.string() */
          candidate_version: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          metric: string;
          /** @sqlType STRING */
          unit: string;
          /** @sqlType STRING */
          metric_tier: string;
          /** @sqlType BOOLEAN */
          lower_is_better: boolean;
          /** @sqlType DOUBLE */
          baseline_value: number;
          /** @sqlType DOUBLE */
          candidate_value: number;
          /** @sqlType DOUBLE */
          delta_absolute: number;
          /** @sqlType DOUBLE */
          delta_pct: number;
          /** @sqlType BOOLEAN */
          improved: boolean;
        }>;
      };
  }
}
