// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    by_model: {
        name: "by_model";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          model: string;
          /** @sqlType BIGINT */
          sessions: number;
          /** @sqlType BIGINT */
          total_tokens: number;
          /** @sqlType DOUBLE */
          est_cost_usd: number;
          /** @sqlType BIGINT */
          tool_calls: number;
        }>;
      };
    by_producer: {
        name: "by_producer";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          producer: string;
          /** @sqlType BIGINT */
          sessions: number;
          /** @sqlType BIGINT */
          total_tokens: number;
          /** @sqlType DOUBLE */
          est_cost_usd: number;
          /** @sqlType BIGINT */
          tool_calls: number;
        }>;
      };
    corpus_summary: {
        name: "corpus_summary";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType INT */
          trace_count: number;
          /** @sqlType BIGINT */
          total_tokens: number;
          /** @sqlType BIGINT */
          total_input_tokens: number;
          /** @sqlType BIGINT */
          total_output_tokens: number;
          /** @sqlType DOUBLE */
          median_tokens: number;
          /** @sqlType DOUBLE */
          mean_tokens: number;
          /** @sqlType DOUBLE */
          p90_tokens: number;
          /** @sqlType BIGINT */
          max_tokens: number;
          /** @sqlType BIGINT */
          min_tokens: number;
          /** @sqlType BIGINT */
          total_tool_calls: number;
          /** @sqlType DOUBLE */
          redundancy_rate: number;
          /** @sqlType DOUBLE */
          total_cost_usd: number;
          /** @sqlType INT */
          priced_traces: number;
          /** @sqlType INT */
          unpriced_traces: number;
        }>;
      };
    high_token_sessions: {
        name: "high_token_sessions";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          trace: string;
          /** @sqlType STRING */
          model: string;
          /** @sqlType BIGINT */
          total_tokens: number;
          /** @sqlType BIGINT */
          input_tokens: number;
          /** @sqlType BIGINT */
          output_tokens: number;
          /** @sqlType INT */
          tools: number;
          /** @sqlType DOUBLE */
          duration_s: number;
          /** @sqlType DOUBLE */
          est_cost_usd: number;
          /** @sqlType BOOLEAN */
          cost_priced: boolean;
          /** @sqlType DOUBLE */
          redundancy_rate: number;
        }>;
      };
    session_token_bars: {
        name: "session_token_bars";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          trace: string;
          /** @sqlType BIGINT */
          total_tokens: number;
        }>;
      };
    tool_waste_files: {
        name: "tool_waste_files";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          trace: string;
          /** @sqlType STRING */
          tool: string;
          /** @sqlType INT */
          repeat_count: number;
          /** @sqlType INT */
          trace_tools: number;
          /** @sqlType STRING */
          path: string;
        }>;
      };
    tool_waste_shell: {
        name: "tool_waste_shell";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          trace: string;
          /** @sqlType STRING */
          tool: string;
          /** @sqlType INT */
          repeat_count: number;
          /** @sqlType INT */
          trace_tools: number;
          /** @sqlType STRING */
          prologue: string;
        }>;
      };
  }
}
